from typing import List
from pydantic import BaseModel, Field


class RACQuery(BaseModel):
    train_no: str
    from_station: str
    to_station: str
    date: str
    current_waitlist_position: int
    current_rac_count: int
    days_to_journey: int
    quota: str = "GN"  # 'GN', 'TQ', 'LD', etc.


class FactorImpact(BaseModel):
    factor: str
    impact: float  # Value between -1.0 and 1.0 showing positive/negative correlation


class RACPrediction(BaseModel):
    confirmation_probability: float
    confidence_interval: List[float] = Field(default_factory=lambda: [0.0, 1.0])
    key_factors: List[FactorImpact] = []
    model_version: str = "XGBoost-v1.2"
    disclaimer: str = "This prediction is generated by an autonomous ML classifier trained on historical IRCTC ticketing statistics and is not a guarantee of travel status."
